### ISSUE TITLE
Template question

### ISSUE THREAD

**Issue by merosoko** [ataranlen/civcraft#59]
How to add new group of templates?I added other styles in the other groups, but do not understand how to make a new group for them, where they add? 
![2016-10-30_18-16-38](https://cloud.githubusercontent.com/assets/19504381/19837603/21e82b34-9ece-11e6-8cdb-048d2da29956.png)

sorry for stupid question :(

**Comment by BenjaminGoGurts** [comment]
You need to add it in the perks.yml

**Comment by ataranlen** [comment]
In the perks.yml add a new item with the prefix of 'template_' in the ID component as below:

```
# ===== Template Sets
    - id: 'template_arctic'
      display_name: 'Arctic Templates'
      simple_name: "arctic"
      item_id: 79
      data: 0
      components:
          - name: 'CustomTemplate'
```

Then you can add templates to that set using a prefix of 'tpl_arctic_' as below:

```
############ ARCTIC THEME
    - id: 'tpl_arctic_camp'
      display_name: 'Arctic Camp'
      item_id: 79
      data: 0
      components:
          - name: 'CustomPersonalTemplate'
            theme: 'arctic'
            template: 'camp'
            id: 'camp'
```
